"""Explicit rejection codes for Bet Manager validation pipeline."""

# Schema & Entity Existence
INVALID_SCHEMA = "INVALID_SCHEMA"
EVENT_NOT_FOUND = "EVENT_NOT_FOUND"
EVENT_FINISHED = "EVENT_FINISHED"
MARKET_NOT_FOUND = "MARKET_NOT_FOUND"
MARKET_SUSPENDED = "MARKET_SUSPENDED"
SELECTION_NOT_FOUND = "SELECTION_NOT_FOUND"

# Freshness & Market Dynamics
STALE_ODDS = "STALE_ODDS"
STALE_EVENT_STATE = "STALE_EVENT_STATE"
PRICE_SLIPPED = "PRICE_SLIPPED"
DUPLICATE_PROPOSAL = "DUPLICATE_PROPOSAL"

# Model & Statistical Hurdles
EDGE_TOO_LOW = "EDGE_TOO_LOW"
CONFIDENCE_TOO_LOW = "CONFIDENCE_TOO_LOW"

# Sport & Rules
UNSUPPORTED_SPORT = "UNSUPPORTED_SPORT"
SPORT_RULE_VIOLATION = "SPORT_RULE_VIOLATION"

# Financial & Risk Policy Limits
STAKE_TOO_LOW = "STAKE_TOO_LOW"
STAKE_LIMIT_EXCEEDED = "STAKE_LIMIT_EXCEEDED"
EXPOSURE_LIMIT = "EXPOSURE_LIMIT"
DAILY_LOSS_LIMIT_EXCEEDED = "DAILY_LOSS_LIMIT_EXCEEDED"
INSUFFICIENT_BANKROLL = "INSUFFICIENT_BANKROLL"
