"""Shared NeuroBet feature construction.

Live inference, online training, LightGBM, backtest, and event archive all
build the same sample dict and call `build_model_input`. Parsers and the
overround grouping live here so backend and ai_service cannot drift.
"""
from .overround import (
    OVERROUND_EXPECTED_SIZE,
    OVERROUND_UNKNOWN,
    accumulate_overround,
    overround_at_latest,
    overround_from_grouped,
    overround_group_key,
)
from .no_vig import no_vig_probability
from .parse import (
    TimerParse,
    pack_timer_entry,
    parse_period_ordinal,
    parse_score_diff,
    parse_score_pair,
    parse_score_sum,
    parse_timer,
    parse_timer_seconds,
    parse_ts_epoch,
    period_index,
    unpack_timer_entry,
)
from .team_form import build_team_form_index, lookup_team_form
from .view import (
    GRU_INPUT_DIM,
    LGB_CATEGORICAL_FEATURES,
    LGB_FEATURE_NAMES,
    MATCH_TIME_NORM_SECONDS,
    MATCH_TIME_UNKNOWN,
    SEQ_LEN,
    TIME_NORM_SECONDS,
    build_gru_sequence,
    build_model_input,
    cutoff_index,
    lgb_feature_row,
    live_sample,
    row_to_sample,
    scale_line_remaining,
    scale_match_score,
    scale_overround,
    scale_score_sum,
    scale_set_points,
    scale_total_line,
    set_team_form_cache,
)
from .vocab import (
    MARKET_FAMILIES,
    NUM_MARKET_FAMILIES,
    NUM_SPORTS,
    SPORT_NAMES,
    TEAM_HASH_BUCKETS,
    market_family_index,
    sport_index,
    team_index,
)

__all__ = [
    "OVERROUND_EXPECTED_SIZE",
    "OVERROUND_UNKNOWN",
    "accumulate_overround",
    "overround_at_latest",
    "overround_from_grouped",
    "overround_group_key",
    "TimerParse",
    "pack_timer_entry",
    "parse_period_ordinal",
    "no_vig_probability",
    "parse_score_diff",
    "parse_score_pair",
    "parse_score_sum",
    "build_team_form_index",
    "lookup_team_form",
    "set_team_form_cache",
    "scale_line_remaining",
    "scale_overround",
    "scale_score_sum",
    "parse_timer",
    "parse_timer_seconds",
    "parse_ts_epoch",
    "period_index",
    "unpack_timer_entry",
    "GRU_INPUT_DIM",
    "LGB_CATEGORICAL_FEATURES",
    "LGB_FEATURE_NAMES",
    "MATCH_TIME_NORM_SECONDS",
    "MATCH_TIME_UNKNOWN",
    "SEQ_LEN",
    "TIME_NORM_SECONDS",
    "build_gru_sequence",
    "build_model_input",
    "cutoff_index",
    "lgb_feature_row",
    "live_sample",
    "row_to_sample",
    "scale_match_score",
    "scale_set_points",
    "scale_total_line",
    "MARKET_FAMILIES",
    "NUM_MARKET_FAMILIES",
    "NUM_SPORTS",
    "SPORT_NAMES",
    "TEAM_HASH_BUCKETS",
    "market_family_index",
    "sport_index",
    "team_index",
]
